spring:
  profiles:
    active: local

cloud.aws:
  region.static: ap-northeast-2
  stack.auto: true

---
spring:
  profiles: local
cloud.aws:
  region.static: ap-northeast-2
  stack.auto: false
---
spring:
  profiles: local